version: '3.3'
services:
  spp-platform:
    build:
      context: .
      dockerfile: Dockerfile-spp-platform
    container_name: spp-platform
    hostname: spp-platform
    ports:
      - "5445:5445"
      - "5450:5450"
      - "5455:5455"
    depends_on:
      - redis
    links:
      - redis
    environment:
      - SPP_CLUSTER_URL=localhost
      - SPP_CLUSTER_NAME=docker
      - SPP_REDIS_HOST=redis
      - SPP_SKYWALKING_HOST=skywalking-oap
      - SPP_DISABLE_JWT=true
  redis:
    image: redis:6.2.1
    container_name: redis
    hostname: redis
